# Generated by Django 6.0.5 on 2026-05-19 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='breast_feeling',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='mood',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
