# Generated by Django 6.0.5 on 2026-05-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dailylog_field_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='source_skin',
            field=models.CharField(db_index=True, default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='pumpingsession',
            name='source_skin',
            field=models.CharField(db_index=True, default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='supplement',
            name='source_skin',
            field=models.CharField(db_index=True, default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='supplementlog',
            name='source_skin',
            field=models.CharField(db_index=True, default='unknown', max_length=32),
        ),
    ]
