# Generated by Django 6.0.5 on 2026-07-02 18:36

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


FOUNDER_USERNAME = 'testusr'
FOUNDER_EMAIL = 'proctologygambler@proton.me'


def create_founder_and_backfill(apps, schema_editor):
    """Create the founder superuser and assign every user=NULL row to them.
    Runs once at migrate time. Password is unusable — set via
    `manage.py changepassword testusr` after migration."""
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('core', 'UserProfile')

    founder, created = User.objects.get_or_create(
        username=FOUNDER_USERNAME,
        defaults={
            'email': FOUNDER_EMAIL,
            'is_staff': True,
            'is_superuser': True,
            'password': make_password(None),
        },
    )

    UserProfile.objects.get_or_create(user=founder)

    for model_name in ('PumpingSession', 'DailyLog', 'Supplement', 'SupplementLog'):
        model = apps.get_model('core', model_name)
        model.objects.filter(user__isnull=True).update(user=founder)


def delete_founder(apps, schema_editor):
    """Reversal: delete the founder (cascades to their data)."""
    User = apps.get_model('auth', 'User')
    User.objects.filter(username=FOUNDER_USERNAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dailylog_source_skin_pumpingsession_source_skin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pooling_consent', models.BooleanField(default=False)),
                ('data_pooling_consent_at', models.DateTimeField(blank=True, null=True)),
                ('has_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=64)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='dailylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pumpingsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pumping_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplementlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplement_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='dailylog',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_dailylog_per_user_date'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.RunPython(create_founder_and_backfill, delete_founder),
    ]
