# Generated by Django 6.0.5 on 2026-07-02 21:40

from django.db import migrations, models


INITIAL_SUGGESTIONS = [
    'Fenugreek',
    'Blessed Thistle',
    "Goat's Rue",
    'Moringa',
    'Domperidone',
    'Shatavari',
    'Saw Palmetto',
    'Alfalfa',
]


def seed_suggestions(apps, schema_editor):
    """Populate the initial suggestion list, matching the hard-coded set
    previously living in core/views.py plus Saw Palmetto and Alfalfa."""
    Suggestion = apps.get_model('core', 'SupplementSuggestion')
    for order, name in enumerate(INITIAL_SUGGESTIONS, start=10):
        Suggestion.objects.get_or_create(
            name=name,
            defaults={'display_order': order, 'is_active': True},
        )


def unseed_suggestions(apps, schema_editor):
    Suggestion = apps.get_model('core', 'SupplementSuggestion')
    Suggestion.objects.filter(name__in=INITIAL_SUGGESTIONS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_ownership'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.RunPython(seed_suggestions, unseed_suggestions),
    ]
