# skins/galactra/copy.py
# ──────────────────────────────────────────────────────────────────────
# Galactra® — Clinical lactation tracker, pharmaceutical-product voice.
# Reads like prescribing information / a drug monograph. Latin/Greek
# medical vocabulary; no emoji; numerical / protocol-coded language.
# Always defers to the user's prescriber. Never gives medical advice.
# Only override _base where the pharma voice lands.
# ──────────────────────────────────────────────────────────────────────

COPY = {
    # ── Brand ──────────────────────────────────────────────────────
    "brand.name":                  "GALACTRA®",
    "brand.tagline":               "A simple induced lactation tracker",
    "brand.emoji":                 "",

    # ── Nav ────────────────────────────────────────────────────────
    "nav.home":                    "Overview",
    "nav.pump":                    "Session",
    "nav.supplements":             "Regimen",
    "nav.daily":                   "Log",
    "nav.progress":                "Data",

    # ── Home / Overview ────────────────────────────────────────────
    "home.welcome":                "Overview",
    "home.start_session":          "Initiate session",
    "home.start_session_sub":      "Timing begins when you press start.",
    "home.start_session_icon":     "",
    "home.today":                  "Today",
    "home.min_pumped":             "Duration",
    "home.sessions":               "Sessions",
    "home.supplements":            "Adherence",
    "home.recent_sessions":        "Recent sessions",
    "home.lifetime_prefix":        "Cumulative pumping duration:",
    "home.lifetime_suffix":        "min",
    "home.no_sessions_yet":        "No sessions on record.",

    # ── Galactra home overlay (per-skin page divergence) ───────────
    "home.protocol_header":        "Protocol overview",
    "home.protocol_indication":    "Induced lactation tracking",
    "home.protocol_day_prefix":    "Day",
    "home.protocol_not_started":   "Not yet initiated",
    "home.isi_title":              "Important safety information",
    "home.isi_brief":              "Galactra is an observational self-tracking tool. Not medical advice. Consult your prescriber before initiating any lactation protocol, galactagogue, or prescription medication.",
    "home.isi_more":               "Read full safety information",
    "home.today_section":          "Today",
    "home.col_sessions":           "Sessions",
    "home.col_duration":           "Duration",
    "home.col_yield":              "Yield",
    "home.col_adherence":          "Adherence",
    "home.next_section":           "Next session",
    "home.last_session_prefix":    "Last session",
    "home.last_session_never":     "No sessions on record. Initiate the first to start the protocol clock.",
    "home.target_interval":        "Target interval: 2–3 h",
    "home.status_recent":          "Recent",
    "home.status_due":             "Due",
    "home.status_overdue":         "Overdue",
    "home.status_not_started":     "Not started",
    "home.cta_initiate":           "Initiate session",
    "home.regimen_section":        "Active regimen",
    "home.regimen_empty":          "No agents currently logged. Add an agent to begin adherence tracking.",
    "home.regimen_link":           "Open full regimen",
    "home.regimen_administered":   "Administered today",
    "home.regimen_pending":        "Pending",
    "home.records_section":        "Recent records",
    "home.records_col_date":       "Date",
    "home.records_col_duration":   "Dur.",
    "home.records_col_left":       "L (mL)",
    "home.records_col_right":      "R (mL)",
    "home.records_col_total":      "Total (mL)",
    "home.records_empty":          "No session records.",
    "home.log_section":            "Today's observation log",
    "home.log_status_complete":    "Recorded",
    "home.log_status_pending":     "Not yet recorded",
    "home.log_link_pending":       "Record observations →",
    "home.log_link_complete":      "Update record →",

    # ── Pump / Session ─────────────────────────────────────────────
    "pump.title":                  "Pumping session",
    "pump.subtitle":               "Standard cadence: every 2–3 h while awake. Adjust per your IBCLC or physician.",
    "pump.ready":                  "Ready to begin.",
    "pump.today_label":            "Today (cumulative):",
    "pump.start":                  "START",
    "pump.stop":                   "STOP",
    "pump.reset":                  "RESET",
    "pump.log_title":              "Record session details",
    "pump.notes_label":            "Clinical notes",
    "pump.left_label":             "Yield, left (mL)",
    "pump.right_label":            "Yield, right (mL)",
    "pump.save":                   "Record session",
    "pump.cancel":                 "Cancel",
    "pump.form_errors_intro":      "Session record could not be saved:",
    "pump.protocol_header":        "Session — pumping protocol",
    "pump.cadence_last":           "Last session",
    "pump.cadence_target":         "Target interval: 2–3 h",
    "pump.in_progress":            "Session in progress",
    "pump.today_col_sessions":     "Sessions",
    "pump.today_col_duration":     "Duration",
    "pump.today_col_yield":        "Yield",
    "pump.discard":                "Discard",

    # ── Daily log ──────────────────────────────────────────────────
    "daily.title":                 "Daily observation log",
    "daily.subtitle":              "Patient-reported outcomes for today.",
    "daily.log_today":             "Record observations",
    "daily.update_today":          "Update today's record",
    "daily.mood_label":            "Affect / mood",
    "daily.mood_hint":             "Select all that apply, or note in free text.",
    "daily.mood_custom_placeholder": "Additional descriptors — comma-separated",
    "daily.breast_label":          "Breast state",
    "daily.breast_hint":           "Select all that apply, or note in free text.",
    "daily.breast_custom_placeholder": "Additional descriptors — comma-separated",
    "daily.energy_label":          "Energy (1–5 scale)",
    "daily.sleep_label":           "Sleep quality (1–5)",
    "daily.hydration_label":       "Hydration (1–5)",
    "daily.stress_label":          "Perceived stress (1–5)",
    "daily.tags_label":            "Additional observations",
    "daily.notes_label":           "Clinical notes",
    "daily.notes_placeholder":     "Free-text observations relevant to today.",
    "daily.form_errors_intro":     "Observation record could not be saved:",
    "daily.save":                  "Record",
    "daily.update":                "Update record",
    "daily.past_entries":          "Prior observations",
    "daily.no_entries":            "No prior records.",
    "daily.past_mood_label":       "Affect",
    "daily.past_breast_label":     "Breast state",

    # ── Supplements / Regimen ──────────────────────────────────────
    "supps.title":                 "Active regimen",
    "supps.subtitle":              "Current galactagogues and daily adherence.",
    "supps.guide_link":            "Galactagogue monograph reference",
    "supps.guide_link_icon":       "",
    "supps.today_checklist":       "Today's adherence",
    "supps.taken_today":           "Administered",
    "supps.mark_taken":            "Mark administered",
    "supps.no_supps":              "No agents in current regimen.",
    "supps.no_supps_hint":         "Add an agent below to begin adherence tracking.",
    "supps.quick_add":             "Common agents",
    "supps.quick_add_hint":        "Quick-fills the agent name only. Confirm dosage and frequency with your prescriber.",
    "supps.add_title":             "Add to regimen",
    "supps.add_button":            "Add to regimen",
    "supps.form_errors_intro":     "Agent could not be added:",
    "supps.delete_confirm":        "Discontinue this agent from the regimen?",
    "supps.form_name_label":       "Agent",
    "supps.form_dosage_label":     "Dosage",
    "supps.form_frequency_label":  "Frequency",
    "supps.form_notes_label":      "Notes",

    # ── Supplement guide ───────────────────────────────────────────
    "guide.title":                 "Galactagogue reference",
    "guide.subtitle":              "Herbal and pharmaceutical agents used in induced lactation. Informational use only; not a substitute for prescriber guidance.",
    "guide.disclaimer_title":      "Important safety information",
    "guide.back_link":             "Return to regimen",

    # ── Progress / Data ────────────────────────────────────────────
    "progress.title":              "Data",
    "progress.subtitle":           "Session metrics, longitudinal.",
    "progress.total_time":         "Total duration",
    "progress.sessions":           "Sessions recorded",
    "progress.volume_tracked":     "Volume recorded",
    "progress.volume_icon":        "Vol.",
    "progress.minutes_per_day":    "Minutes per day",
    "progress.no_sessions":        "No sessions recorded in the selected window.",
    "progress.daily_breakdown":    "Daily breakdown",
    "progress.no_data_window":     "No data in window.",

    # ── Footer ─────────────────────────────────────────────────────
    "footer.message":              "Important safety information — Galactra is an observational self-tracking tool. It does not diagnose, treat, cure, or prevent any condition. Consult your physician, IBCLC, or qualified healthcare provider before starting or modifying any lactation protocol, galactagogue, or prescription medication. All data is kept on this device.",
    "footer.theme_label":          "Interface:",

    # ── Encouragement (suppressed via feature flag; kept neutral) ──
    "encourage.first_session":     "Session recorded.",
    "encourage.streak_3":          "Three consecutive session days logged.",
    "encourage.streak_7":          "Seven consecutive session days logged.",
    "encourage.output_increase":   "Upward trend observed in recent yield data.",
    "encourage.keep_going":        "Continue per protocol.",
}
