"""
Django settings for lactea_backend project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load `.env` file if present (dependency-free; no python-dotenv needed).
# This sets os.environ values from KEY=VALUE lines, ignoring comments/blanks.
_env_file = BASE_DIR / '.env'
if _env_file.exists():
    for _line in _env_file.read_text().splitlines():
        _line = _line.strip()
        if not _line or _line.startswith('#') or '=' not in _line:
            continue
        _key, _, _value = _line.partition('=')
        os.environ.setdefault(_key.strip(), _value.strip().strip('"').strip("'"))


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-dev-fallback-set-SECRET_KEY-in-.env-before-deploying',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your apps
    'core',

    # Third-party
    'django_htmx',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'core.middleware.SkinMiddleware',
    # PaywallMiddleware runs AFTER SkinMiddleware (needs request.skin) and
    # AFTER AuthenticationMiddleware (needs request.user). Gates the
    # PAYWALL_SKIN behind an authenticated + has_paid check.
    'core.middleware.PaywallMiddleware',
]

ROOT_URLCONF = 'lactea_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        # APP_DIRS must be False when 'loaders' is set explicitly below.
        # The AppDirectoriesLoader is still included in the loaders list,
        # so admin / third-party app templates still resolve.
        'APP_DIRS': False,
        'OPTIONS': {
            'loaders': [
                # Skin-aware overlay: templates/skins/<current_skin>/<name>
                # is checked before the shared templates/<name>.
                'skins.template_overlay.SkinOverlayLoader',
                'django.template.loaders.app_directories.Loader',
            ],
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.skin_context',
            ],
        },
    },
]


# Per-host skin lock. When a request's Host header matches a key here,
# the skin is forced (cookie toggle is ignored) and request.skin_locked
# is set to True so the UI can hide cross-skin switchers.
#
# Empty on dev (any host → cookie behavior). Populate via env in prod:
#   SKIN_BY_HOST="lactea.example.com=cow,vialactea.example.com=via_lactea,..."
SKIN_BY_HOST = {}
_skin_by_host_env = os.environ.get('SKIN_BY_HOST', '').strip()
if _skin_by_host_env:
    for _pair in _skin_by_host_env.split(','):
        _host, _, _skin = _pair.partition('=')
        _host = _host.strip()
        _skin = _skin.strip()
        if _host and _skin:
            SKIN_BY_HOST[_host] = _skin

WSGI_APPLICATION = 'lactea_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INTERNAL_IPS = ['127.0.0.1']


# Auth flow. Django's login_required redirects to LOGIN_URL; successful
# login/logout redirect to *_REDIRECT_URL. Signup is a custom view in
# core.views (Django doesn't ship one) — see core/urls.py.
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'login'

# Password reset emails print to the console in dev. Real SMTP lands in T5
# with hosting. See https://docs.djangoproject.com/en/6.0/topics/email/
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'support@galactra.app')


# --- Stripe (T2 purchase gate) ---
# Test keys pinned to the Stripe test sandbox; live keys never touch this
# repo (populate from a prod-only secret store when we ship). See
# tranche_notes.md → T2 for the account walkthrough.
STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_PRICE_ID = os.environ.get('STRIPE_PRICE_ID', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')

# Which skin (by internal name) requires purchase to access.
# Unified Lactea product per docs/design-pivot-2026-08-27.md — internal
# identifier stays `via_lactea`, user-facing brand is "Lactea".
PAYWALL_SKIN = 'via_lactea'
